name = "FerriteCon2023"
uuid = "8b6177d4-baca-44ee-a0fb-9570f97f30e9"
authors = ["Kim Louisa Auth <auth@chalmers.se> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
